apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.container.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.container.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
  labels:
    app: {{ .Values.container.name }}
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Values.container.name }}
  ports:
    - port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      protocol: {{ .Values.service.protocol }} 
