apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-object-factory
  labels:
    app: hash-object-factory
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hash-object-factory
  template:
    metadata:
      labels:
        app: hash-object-factory
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.preStopHook }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "{{ .Values.preStopHook.sleepSeconds }}"]
          {{- end }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
              httpHeaders:
                {{- toYaml .Values.readinessProbe.httpHeaders | nindent 16 }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{.Values.readinessProbe.timeoutSeconds}}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }} 